#!/bin/bash
#######################################################
# Example cronjob which can be ran on some secure
# server which will then take care of changing the passwords
# on the server farm on regular intervals, for example
# 24h or 1 per week.
#
# Author: Juhapekka Piiroinen <jp@1337.fi>
# License: MIT
#
# Copyright 2019 Juhapekka Piiroinen <jp@1337.fi>
# 
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom
# the Software is furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#######################################################
set -e

DIRPATH=`dirname $0`
export ACCOUNT_NAME=$1

if [[ -z ${SERVER_NAME} ]]; then
    export SERVER_NAME=servers
fi

pushd ${DIRPATH} &> /dev/null
    export ACCOUNT_USERNAME=`cat .account_name`
    export ACCOUNT_PASSWORD=`cat .account_password`
    make login
    make update
    make logout
popd &> /dev/null
